# create a workflow that will be triggered on push to main branch and will deploy the app to the production environment to self-hosted runner
name: CD to CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted]
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Kill existing process
        run: kill $(lsof -t -i:9292) || true && echo "Process killed" || echo "No process to kill"

      - name: Deploy
        run: yarn start || true && echo "Process started" || echo "No process to start"

      - name: Clean up
        if: always()
        run: npm uninstall -g yarn
