# create a workflow that will be triggered on push to main branch and will deploy the app to the production environment to self-hosted runner
name: CD to CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted]
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"

      - name: Pull latest code
        run: git pull origin main

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Deploy with PM2
        run: echo "Deploying with PM2" > deploy.log && pm2 deploy ecosystem.config.js production --force >> deploy.log

      - name: Clean up
        if: always()
        run: npm uninstall -g yarn
