# create a workflow that will be triggered on push to main branch and will deploy the app to the production environment to self-hosted runner
name: CD to CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted]
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"

      - name: Pull latest code
        run: git pull origin main

      - name: Install PM2 globally (if not already installed)
        run: npm install -g pm2

      - name: cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
            ${{ runner.os }}-node-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - name: PM2 init (if not already initialized)
        run: pm2 init

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Deploy with PM2
        run: pm2 start "npm run start" --name "app"

      - name: Clean up
        if: always()
        run: npm uninstall -g yarn
